# Generated by Django 4.2.10 on 2024-07-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_alter_website_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="website",
            name="last_updated",
        ),
        migrations.AlterField(
            model_name="website",
            name="last_hash",
            field=models.TimeField(default=None),
        ),
    ]
