# Generated by Django 4.2.10 on 2024-07-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_alter_website_last_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="last_hash",
            field=models.TextField(default="None"),
        ),
    ]
