# Generated by Django 4.2.10 on 2024-07-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_alter_website_last_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="name",
            field=models.CharField(default="None", max_length=100),
        ),
    ]
